services:
  web:
    build: .
    ports:
      - "4000:8080"
    environment:
      - NGINX_PROTOCOL=
    volumes:
      - ./nginx-config/nginxconfig.io:/etc/nginx/nginxconfig.io
      - ./nginx-config/templates:/etc/nginx/templates
      - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html
